/*
 * Stub for class org.opencv.core.MatOfDouble
 * Generated by Sapphire Compiler (sc).
 */
package org.opencv.core.stubs;


public final class MatOfDouble_Stub extends org.opencv.core.MatOfDouble implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public MatOfDouble_Stub () {
        super();
    }

    public MatOfDouble_Stub (org.opencv.core.Mat $param_Mat_1) {
        super($param_Mat_1);
    }

    public MatOfDouble_Stub (double[] $param_arrayOf_double_1) {
        super($param_arrayOf_double_1);
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of toList()
    public java.util.List toList() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.toList();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.util.List<java.lang.Double> org.opencv.core.MatOfDouble.toList()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.List) $__result);
    }

    // Implementation of toArray()
    public double[] toArray() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.toArray();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public double[] org.opencv.core.MatOfDouble.toArray()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((double[]) $__result);
    }

    // Implementation of fromNativeAddr(long)
    public org.opencv.core.MatOfDouble fromNativeAddr(long $param_long_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.fromNativeAddr( $param_long_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public static org.opencv.core.MatOfDouble org.opencv.core.MatOfDouble.fromNativeAddr(long)";
                $__params.add($param_long_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((org.opencv.core.MatOfDouble) $__result);
    }

    // Implementation of fromList(List)
    public void fromList(java.util.List $param_List_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.fromList( $param_List_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void org.opencv.core.MatOfDouble.fromList(java.util.List<java.lang.Double>)";
                $__params.add($param_List_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of fromArray(double[])
    public void fromArray(double[] $param_arrayOf_double_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.fromArray( $param_arrayOf_double_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void org.opencv.core.MatOfDouble.fromArray(double...)";
                $__params.add($param_arrayOf_double_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of alloc(int)
    public void alloc(int $param_int_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.alloc( $param_int_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void org.opencv.core.MatOfDouble.alloc(int)";
                $__params.add($param_int_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
