/*
 * Stub for class boofcv.alg.feature.detect.intensity.impl.ImplShiTomasiCorner_S16
 * Generated by Sapphire Compiler (sc).
 */
package boofcv.alg.feature.detect.intensity.impl.stubs;


public final class ImplShiTomasiCorner_S16_Stub extends boofcv.alg.feature.detect.intensity.impl.ImplShiTomasiCorner_S16 implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public ImplShiTomasiCorner_S16_Stub (int $param_int_1, boofcv.core.image.GeneralizedImageOps $param_GeneralizedImageOps_2) {
        super($param_int_1, $param_GeneralizedImageOps_2);
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }


}
