/*
 * Stub for class boofcv.alg.feature.detect.intensity.impl.ImplFastIntensity9
 * Generated by Sapphire Compiler (sc).
 */
package boofcv.alg.feature.detect.intensity.impl.stubs;


public final class ImplFastIntensity9_Stub extends boofcv.alg.feature.detect.intensity.impl.ImplFastIntensity9 implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public ImplFastIntensity9_Stub (boofcv.alg.feature.detect.intensity.impl.FastHelper $param_FastHelper_1) {
        super($param_FastHelper_1);
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }


}
