/*
 * Stub for class boofcv.alg.filter.binary.impl.ImplBinaryBorderOps
 * Generated by Sapphire Compiler (sc).
 */
package boofcv.alg.filter.binary.impl.stubs;


public final class ImplBinaryBorderOps_Stub extends boofcv.alg.filter.binary.impl.ImplBinaryBorderOps implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public ImplBinaryBorderOps_Stub () {
        super();
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of removePointNoise(GrayU8, GrayU8, ImageBorderValue)
    public void removePointNoise(boofcv.struct.image.GrayU8 $param_GrayU8_1, boofcv.struct.image.GrayU8 $param_GrayU8_2, boofcv.core.image.border.ImageBorderValue $param_ImageBorderValue_3) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.removePointNoise( $param_GrayU8_1,  $param_GrayU8_2,  $param_ImageBorderValue_3);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.alg.filter.binary.impl.ImplBinaryBorderOps.removePointNoise(boofcv.struct.image.GrayU8,boofcv.struct.image.GrayU8,boofcv.core.image.border.ImageBorderValue)";
                $__params.add($param_GrayU8_1);
                $__params.add($param_GrayU8_2);
                $__params.add($param_ImageBorderValue_3);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of erode8(GrayU8, GrayU8, ImageBorderValue)
    public void erode8(boofcv.struct.image.GrayU8 $param_GrayU8_1, boofcv.struct.image.GrayU8 $param_GrayU8_2, boofcv.core.image.border.ImageBorderValue $param_ImageBorderValue_3) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.erode8( $param_GrayU8_1,  $param_GrayU8_2,  $param_ImageBorderValue_3);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.alg.filter.binary.impl.ImplBinaryBorderOps.erode8(boofcv.struct.image.GrayU8,boofcv.struct.image.GrayU8,boofcv.core.image.border.ImageBorderValue)";
                $__params.add($param_GrayU8_1);
                $__params.add($param_GrayU8_2);
                $__params.add($param_ImageBorderValue_3);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of erode4(GrayU8, GrayU8, ImageBorderValue)
    public void erode4(boofcv.struct.image.GrayU8 $param_GrayU8_1, boofcv.struct.image.GrayU8 $param_GrayU8_2, boofcv.core.image.border.ImageBorderValue $param_ImageBorderValue_3) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.erode4( $param_GrayU8_1,  $param_GrayU8_2,  $param_ImageBorderValue_3);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.alg.filter.binary.impl.ImplBinaryBorderOps.erode4(boofcv.struct.image.GrayU8,boofcv.struct.image.GrayU8,boofcv.core.image.border.ImageBorderValue)";
                $__params.add($param_GrayU8_1);
                $__params.add($param_GrayU8_2);
                $__params.add($param_ImageBorderValue_3);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of edge8(GrayU8, GrayU8, ImageBorderValue)
    public void edge8(boofcv.struct.image.GrayU8 $param_GrayU8_1, boofcv.struct.image.GrayU8 $param_GrayU8_2, boofcv.core.image.border.ImageBorderValue $param_ImageBorderValue_3) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.edge8( $param_GrayU8_1,  $param_GrayU8_2,  $param_ImageBorderValue_3);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.alg.filter.binary.impl.ImplBinaryBorderOps.edge8(boofcv.struct.image.GrayU8,boofcv.struct.image.GrayU8,boofcv.core.image.border.ImageBorderValue)";
                $__params.add($param_GrayU8_1);
                $__params.add($param_GrayU8_2);
                $__params.add($param_ImageBorderValue_3);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of edge4(GrayU8, GrayU8, ImageBorderValue)
    public boofcv.struct.image.GrayU8 edge4(boofcv.struct.image.GrayU8 $param_GrayU8_1, boofcv.struct.image.GrayU8 $param_GrayU8_2, boofcv.core.image.border.ImageBorderValue $param_ImageBorderValue_3) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.edge4( $param_GrayU8_1,  $param_GrayU8_2,  $param_ImageBorderValue_3);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public boofcv.struct.image.GrayU8 boofcv.alg.filter.binary.impl.ImplBinaryBorderOps.edge4(boofcv.struct.image.GrayU8,boofcv.struct.image.GrayU8,boofcv.core.image.border.ImageBorderValue)";
                $__params.add($param_GrayU8_1);
                $__params.add($param_GrayU8_2);
                $__params.add($param_ImageBorderValue_3);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((boofcv.struct.image.GrayU8) $__result);
    }

    // Implementation of dilate8(GrayU8, GrayU8, ImageBorderValue)
    public void dilate8(boofcv.struct.image.GrayU8 $param_GrayU8_1, boofcv.struct.image.GrayU8 $param_GrayU8_2, boofcv.core.image.border.ImageBorderValue $param_ImageBorderValue_3) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.dilate8( $param_GrayU8_1,  $param_GrayU8_2,  $param_ImageBorderValue_3);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.alg.filter.binary.impl.ImplBinaryBorderOps.dilate8(boofcv.struct.image.GrayU8,boofcv.struct.image.GrayU8,boofcv.core.image.border.ImageBorderValue)";
                $__params.add($param_GrayU8_1);
                $__params.add($param_GrayU8_2);
                $__params.add($param_ImageBorderValue_3);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of dilate4(GrayU8, GrayU8, ImageBorderValue)
    public void dilate4(boofcv.struct.image.GrayU8 $param_GrayU8_1, boofcv.struct.image.GrayU8 $param_GrayU8_2, boofcv.core.image.border.ImageBorderValue $param_ImageBorderValue_3) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.dilate4( $param_GrayU8_1,  $param_GrayU8_2,  $param_ImageBorderValue_3);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.alg.filter.binary.impl.ImplBinaryBorderOps.dilate4(boofcv.struct.image.GrayU8,boofcv.struct.image.GrayU8,boofcv.core.image.border.ImageBorderValue)";
                $__params.add($param_GrayU8_1);
                $__params.add($param_GrayU8_2);
                $__params.add($param_ImageBorderValue_3);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
