/*
 * Stub for class boofcv.struct.image.GrayS64
 * Generated by Sapphire Compiler (sc).
 */
package boofcv.struct.image.stubs;


public final class GrayS64_Stub extends boofcv.struct.image.GrayS64 implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public GrayS64_Stub () {
        super();
    }

    public GrayS64_Stub (int $param_int_1, int $param_int_2) {
        super($param_int_1, $param_int_2);
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of unsafe_set(int, int, long)
    public void unsafe_set(int $param_int_1, int $param_int_2, long $param_long_3) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.unsafe_set( $param_int_1,  $param_int_2,  $param_long_3);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.struct.image.GrayS64.unsafe_set(int,int,long)";
                $__params.add($param_int_1);
                $__params.add($param_int_2);
                $__params.add($param_long_3);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of unsafe_get(int, int)
    public long unsafe_get(int $param_int_1, int $param_int_2) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.unsafe_get( $param_int_1,  $param_int_2);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public long boofcv.struct.image.GrayS64.unsafe_get(int,int)";
                $__params.add($param_int_1);
                $__params.add($param_int_2);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.Long) $__result).longValue();
    }

    // Implementation of setData(long[])
    public void setData(long[] $param_arrayOf_long_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.setData( $param_arrayOf_long_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.struct.image.GrayS64.setData(long[])";
                $__params.add($param_arrayOf_long_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of set(int, int, long)
    public void set(int $param_int_1, int $param_int_2, long $param_long_3) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.set( $param_int_1,  $param_int_2,  $param_long_3);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.struct.image.GrayS64.set(int,int,long)";
                $__params.add($param_int_1);
                $__params.add($param_int_2);
                $__params.add($param_long_3);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of getDataType()
    public boofcv.struct.image.ImageDataType getDataType() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getDataType();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public boofcv.struct.image.ImageDataType boofcv.struct.image.GrayS64.getDataType()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((boofcv.struct.image.ImageDataType) $__result);
    }

    // Implementation of getData()
    public long[] getData() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getData();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public long[] boofcv.struct.image.GrayS64.getData()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((long[]) $__result);
    }

    // Implementation of get(int, int)
    public long get(int $param_int_1, int $param_int_2) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.get( $param_int_1,  $param_int_2);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public long boofcv.struct.image.GrayS64.get(int,int)";
                $__params.add($param_int_1);
                $__params.add($param_int_2);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.Long) $__result).longValue();
    }

    // Implementation of createNew(int, int)
    public boofcv.struct.image.GrayS64 createNew(int $param_int_1, int $param_int_2) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.createNew( $param_int_1,  $param_int_2);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public boofcv.struct.image.GrayS64 boofcv.struct.image.GrayS64.createNew(int,int)";
                $__params.add($param_int_1);
                $__params.add($param_int_2);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((boofcv.struct.image.GrayS64) $__result);
    }
}
