/*
 * Stub for class boofcv.struct.image.GrayU16
 * Generated by Sapphire Compiler (sc).
 */
package boofcv.struct.image.stubs;


public final class GrayU16_Stub extends boofcv.struct.image.GrayU16 implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public GrayU16_Stub () {
        super();
    }

    public GrayU16_Stub (int $param_int_1, int $param_int_2) {
        super($param_int_1, $param_int_2);
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of unsafe_get(int, int)
    public int unsafe_get(int $param_int_1, int $param_int_2) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.unsafe_get( $param_int_1,  $param_int_2);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public int boofcv.struct.image.GrayU16.unsafe_get(int,int)";
                $__params.add($param_int_1);
                $__params.add($param_int_2);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.Integer) $__result).intValue();
    }

    // Implementation of getDataType()
    public boofcv.struct.image.ImageDataType getDataType() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getDataType();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public boofcv.struct.image.ImageDataType boofcv.struct.image.GrayU16.getDataType()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((boofcv.struct.image.ImageDataType) $__result);
    }

    // Implementation of createNew(int, int)
    public boofcv.struct.image.GrayU16 createNew(int $param_int_1, int $param_int_2) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.createNew( $param_int_1,  $param_int_2);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public boofcv.struct.image.GrayU16 boofcv.struct.image.GrayU16.createNew(int,int)";
                $__params.add($param_int_1);
                $__params.add($param_int_2);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((boofcv.struct.image.GrayU16) $__result);
    }
}
