/*
 * Stub for class boofcv.core.image.border.ImageBorderValue.Value_IL_F64
 * Generated by Sapphire Compiler (sc).
 */
package boofcv.core.image.border.stubs;


public final class ImageBorderValue$Value_IL_F64_Stub extends boofcv.core.image.border.ImageBorderValue.Value_IL_F64 implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public ImageBorderValue$Value_IL_F64_Stub (double $param_double_1) {
        super($param_double_1);
    }

    public ImageBorderValue$Value_IL_F64_Stub (boofcv.struct.image.InterleavedF64 $param_InterleavedF64_1, double $param_double_2) {
        super($param_InterleavedF64_1, $param_double_2);
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of setOutside(int, int, double[])
    public void setOutside(int $param_int_1, int $param_int_2, double[] $param_arrayOf_double_3) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.setOutside( $param_int_1,  $param_int_2,  $param_arrayOf_double_3);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.core.image.border.ImageBorderValue$Value_IL_F64.setOutside(int,int,double[])";
                $__params.add($param_int_1);
                $__params.add($param_int_2);
                $__params.add($param_arrayOf_double_3);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of getOutside(int, int, double[])
    public void getOutside(int $param_int_1, int $param_int_2, double[] $param_arrayOf_double_3) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.getOutside( $param_int_1,  $param_int_2,  $param_arrayOf_double_3);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.core.image.border.ImageBorderValue$Value_IL_F64.getOutside(int,int,double[])";
                $__params.add($param_int_1);
                $__params.add($param_int_2);
                $__params.add($param_arrayOf_double_3);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
