/*
 * Stub for class boofcv.struct.image.InterleavedS64
 * Generated by Sapphire Compiler (sc).
 */
package boofcv.struct.image.stubs;


public final class InterleavedS64_Stub extends boofcv.struct.image.InterleavedS64 implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public InterleavedS64_Stub () {
        super();
    }

    public InterleavedS64_Stub (int $param_int_1, int $param_int_2, int $param_int_3) {
        super($param_int_1, $param_int_2, $param_int_3);
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of unsafe_set(int, int, long[])
    public void unsafe_set(int $param_int_1, int $param_int_2, long[] $param_arrayOf_long_3) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.unsafe_set( $param_int_1,  $param_int_2,  $param_arrayOf_long_3);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.struct.image.InterleavedS64.unsafe_set(int,int,long...)";
                $__params.add($param_int_1);
                $__params.add($param_int_2);
                $__params.add($param_arrayOf_long_3);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of unsafe_get(int, int, long[])
    public void unsafe_get(int $param_int_1, int $param_int_2, long[] $param_arrayOf_long_3) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.unsafe_get( $param_int_1,  $param_int_2,  $param_arrayOf_long_3);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.struct.image.InterleavedS64.unsafe_get(int,int,long[])";
                $__params.add($param_int_1);
                $__params.add($param_int_2);
                $__params.add($param_arrayOf_long_3);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of setBand(int, int, int, long)
    public void setBand(int $param_int_1, int $param_int_2, int $param_int_3, long $param_long_4) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.setBand( $param_int_1,  $param_int_2,  $param_int_3,  $param_long_4);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.struct.image.InterleavedS64.setBand(int,int,int,long)";
                $__params.add($param_int_1);
                $__params.add($param_int_2);
                $__params.add($param_int_3);
                $__params.add($param_long_4);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of set(int, int, long[])
    public void set(int $param_int_1, int $param_int_2, long[] $param_arrayOf_long_3) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.set( $param_int_1,  $param_int_2,  $param_arrayOf_long_3);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.struct.image.InterleavedS64.set(int,int,long...)";
                $__params.add($param_int_1);
                $__params.add($param_int_2);
                $__params.add($param_arrayOf_long_3);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of getDataType()
    public boofcv.struct.image.ImageDataType getDataType() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getDataType();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public boofcv.struct.image.ImageDataType boofcv.struct.image.InterleavedS64.getDataType()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((boofcv.struct.image.ImageDataType) $__result);
    }

    // Implementation of getBand(int, int, int)
    public long getBand(int $param_int_1, int $param_int_2, int $param_int_3) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getBand( $param_int_1,  $param_int_2,  $param_int_3);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public long boofcv.struct.image.InterleavedS64.getBand(int,int,int)";
                $__params.add($param_int_1);
                $__params.add($param_int_2);
                $__params.add($param_int_3);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.Long) $__result).longValue();
    }

    // Implementation of get(int, int, long[])
    public long[] get(int $param_int_1, int $param_int_2, long[] $param_arrayOf_long_3) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.get( $param_int_1,  $param_int_2,  $param_arrayOf_long_3);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public long[] boofcv.struct.image.InterleavedS64.get(int,int,long[])";
                $__params.add($param_int_1);
                $__params.add($param_int_2);
                $__params.add($param_arrayOf_long_3);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((long[]) $__result);
    }

    // Implementation of createNew(int, int)
    public boofcv.struct.image.InterleavedS64 createNew(int $param_int_1, int $param_int_2) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.createNew( $param_int_1,  $param_int_2);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public boofcv.struct.image.InterleavedS64 boofcv.struct.image.InterleavedS64.createNew(int,int)";
                $__params.add($param_int_1);
                $__params.add($param_int_2);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((boofcv.struct.image.InterleavedS64) $__result);
    }
}
