/*
 * Stub for class boofcv.alg.feature.detect.edge.impl.ImplEdgeNonMaxSuppressionCrude
 * Generated by Sapphire Compiler (sc).
 */
package boofcv.alg.feature.detect.edge.impl.stubs;


public final class ImplEdgeNonMaxSuppressionCrude_Stub extends boofcv.alg.feature.detect.edge.impl.ImplEdgeNonMaxSuppressionCrude implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public ImplEdgeNonMaxSuppressionCrude_Stub () {
        super();
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of inner4(GrayF32, GrayS32, GrayS32, GrayF32)
    public void inner4(boofcv.struct.image.GrayF32 $param_GrayF32_1, boofcv.struct.image.GrayS32 $param_GrayS32_2, boofcv.struct.image.GrayS32 $param_GrayS32_3, boofcv.struct.image.GrayF32 $param_GrayF32_4) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.inner4( $param_GrayF32_1,  $param_GrayS32_2,  $param_GrayS32_3,  $param_GrayF32_4);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.alg.feature.detect.edge.impl.ImplEdgeNonMaxSuppressionCrude.inner4(boofcv.struct.image.GrayF32,boofcv.struct.image.GrayS32,boofcv.struct.image.GrayS32,boofcv.struct.image.GrayF32)";
                $__params.add($param_GrayF32_1);
                $__params.add($param_GrayS32_2);
                $__params.add($param_GrayS32_3);
                $__params.add($param_GrayF32_4);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of inner4(GrayF32, GrayS16, GrayS16, GrayF32)
    public void inner4(boofcv.struct.image.GrayF32 $param_GrayF32_1, boofcv.struct.image.GrayS16 $param_GrayS16_2, boofcv.struct.image.GrayS16 $param_GrayS16_3, boofcv.struct.image.GrayF32 $param_GrayF32_4) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.inner4( $param_GrayF32_1,  $param_GrayS16_2,  $param_GrayS16_3,  $param_GrayF32_4);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.alg.feature.detect.edge.impl.ImplEdgeNonMaxSuppressionCrude.inner4(boofcv.struct.image.GrayF32,boofcv.struct.image.GrayS16,boofcv.struct.image.GrayS16,boofcv.struct.image.GrayF32)";
                $__params.add($param_GrayF32_1);
                $__params.add($param_GrayS16_2);
                $__params.add($param_GrayS16_3);
                $__params.add($param_GrayF32_4);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of inner4(GrayF32, GrayF32, GrayF32, GrayF32)
    public void inner4(boofcv.struct.image.GrayF32 $param_GrayF32_1, boofcv.struct.image.GrayF32 $param_GrayF32_2, boofcv.struct.image.GrayF32 $param_GrayF32_3, boofcv.struct.image.GrayF32 $param_GrayF32_4) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.inner4( $param_GrayF32_1,  $param_GrayF32_2,  $param_GrayF32_3,  $param_GrayF32_4);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.alg.feature.detect.edge.impl.ImplEdgeNonMaxSuppressionCrude.inner4(boofcv.struct.image.GrayF32,boofcv.struct.image.GrayF32,boofcv.struct.image.GrayF32,boofcv.struct.image.GrayF32)";
                $__params.add($param_GrayF32_1);
                $__params.add($param_GrayF32_2);
                $__params.add($param_GrayF32_3);
                $__params.add($param_GrayF32_4);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of border4(GrayF32, GrayI, GrayI, GrayF32, FactoryImageBorderAlgs, ImageBorderValue)
    public void border4(boofcv.struct.image.GrayF32 $param_GrayF32_1, boofcv.struct.image.GrayI $param_GrayI_2, boofcv.struct.image.GrayI $param_GrayI_3, boofcv.struct.image.GrayF32 $param_GrayF32_4, boofcv.core.image.border.FactoryImageBorderAlgs $param_FactoryImageBorderAlgs_5, boofcv.core.image.border.ImageBorderValue $param_ImageBorderValue_6) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.border4( $param_GrayF32_1,  $param_GrayI_2,  $param_GrayI_3,  $param_GrayF32_4,  $param_FactoryImageBorderAlgs_5,  $param_ImageBorderValue_6);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.alg.feature.detect.edge.impl.ImplEdgeNonMaxSuppressionCrude.border4(boofcv.struct.image.GrayF32,boofcv.struct.image.GrayI,boofcv.struct.image.GrayI,boofcv.struct.image.GrayF32,boofcv.core.image.border.FactoryImageBorderAlgs,boofcv.core.image.border.ImageBorderValue)";
                $__params.add($param_GrayF32_1);
                $__params.add($param_GrayI_2);
                $__params.add($param_GrayI_3);
                $__params.add($param_GrayF32_4);
                $__params.add($param_FactoryImageBorderAlgs_5);
                $__params.add($param_ImageBorderValue_6);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of border4(GrayF32, GrayF32, GrayF32, GrayF32, FactoryImageBorderAlgs, ImageBorderValue)
    public void border4(boofcv.struct.image.GrayF32 $param_GrayF32_1, boofcv.struct.image.GrayF32 $param_GrayF32_2, boofcv.struct.image.GrayF32 $param_GrayF32_3, boofcv.struct.image.GrayF32 $param_GrayF32_4, boofcv.core.image.border.FactoryImageBorderAlgs $param_FactoryImageBorderAlgs_5, boofcv.core.image.border.ImageBorderValue $param_ImageBorderValue_6) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.border4( $param_GrayF32_1,  $param_GrayF32_2,  $param_GrayF32_3,  $param_GrayF32_4,  $param_FactoryImageBorderAlgs_5,  $param_ImageBorderValue_6);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.alg.feature.detect.edge.impl.ImplEdgeNonMaxSuppressionCrude.border4(boofcv.struct.image.GrayF32,boofcv.struct.image.GrayF32,boofcv.struct.image.GrayF32,boofcv.struct.image.GrayF32,boofcv.core.image.border.FactoryImageBorderAlgs,boofcv.core.image.border.ImageBorderValue)";
                $__params.add($param_GrayF32_1);
                $__params.add($param_GrayF32_2);
                $__params.add($param_GrayF32_3);
                $__params.add($param_GrayF32_4);
                $__params.add($param_FactoryImageBorderAlgs_5);
                $__params.add($param_ImageBorderValue_6);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
