/*
 * Stub for class boofcv.alg.filter.convolve.ConvolveNormalized
 * Generated by Sapphire Compiler (sc).
 */
package boofcv.alg.filter.convolve.stubs;


public final class ConvolveNormalized_Stub extends boofcv.alg.filter.convolve.ConvolveNormalized implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public ConvolveNormalized_Stub () {
        super();
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of vertical(Kernel1D_I32, GrayU8, GrayI8, InputSanityCheck, ConvolveNormalizedNaive, ConvolveImageNoBorder, ConvolveNormalized_JustBorder)
    public void vertical(boofcv.struct.convolve.Kernel1D_I32 $param_Kernel1D_I32_1, boofcv.struct.image.GrayU8 $param_GrayU8_2, boofcv.struct.image.GrayI8 $param_GrayI8_3, boofcv.alg.InputSanityCheck $param_InputSanityCheck_4, boofcv.alg.filter.convolve.normalized.ConvolveNormalizedNaive $param_ConvolveNormalizedNaive_5, boofcv.alg.filter.convolve.ConvolveImageNoBorder $param_ConvolveImageNoBorder_6, boofcv.alg.filter.convolve.normalized.ConvolveNormalized_JustBorder $param_ConvolveNormalized_JustBorder_7) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.vertical( $param_Kernel1D_I32_1,  $param_GrayU8_2,  $param_GrayI8_3,  $param_InputSanityCheck_4,  $param_ConvolveNormalizedNaive_5,  $param_ConvolveImageNoBorder_6,  $param_ConvolveNormalized_JustBorder_7);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.alg.filter.convolve.ConvolveNormalized.vertical(boofcv.struct.convolve.Kernel1D_I32,boofcv.struct.image.GrayU8,boofcv.struct.image.GrayI8,boofcv.alg.InputSanityCheck,boofcv.alg.filter.convolve.normalized.ConvolveNormalizedNaive,boofcv.alg.filter.convolve.ConvolveImageNoBorder,boofcv.alg.filter.convolve.normalized.ConvolveNormalized_JustBorder)";
                $__params.add($param_Kernel1D_I32_1);
                $__params.add($param_GrayU8_2);
                $__params.add($param_GrayI8_3);
                $__params.add($param_InputSanityCheck_4);
                $__params.add($param_ConvolveNormalizedNaive_5);
                $__params.add($param_ConvolveImageNoBorder_6);
                $__params.add($param_ConvolveNormalized_JustBorder_7);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of vertical(Kernel1D_I32, GrayS32, GrayS32, InputSanityCheck, ConvolveNormalizedNaive, ConvolveImageNoBorder, ConvolveNormalized_JustBorder)
    public void vertical(boofcv.struct.convolve.Kernel1D_I32 $param_Kernel1D_I32_1, boofcv.struct.image.GrayS32 $param_GrayS32_2, boofcv.struct.image.GrayS32 $param_GrayS32_3, boofcv.alg.InputSanityCheck $param_InputSanityCheck_4, boofcv.alg.filter.convolve.normalized.ConvolveNormalizedNaive $param_ConvolveNormalizedNaive_5, boofcv.alg.filter.convolve.ConvolveImageNoBorder $param_ConvolveImageNoBorder_6, boofcv.alg.filter.convolve.normalized.ConvolveNormalized_JustBorder $param_ConvolveNormalized_JustBorder_7) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.vertical( $param_Kernel1D_I32_1,  $param_GrayS32_2,  $param_GrayS32_3,  $param_InputSanityCheck_4,  $param_ConvolveNormalizedNaive_5,  $param_ConvolveImageNoBorder_6,  $param_ConvolveNormalized_JustBorder_7);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.alg.filter.convolve.ConvolveNormalized.vertical(boofcv.struct.convolve.Kernel1D_I32,boofcv.struct.image.GrayS32,boofcv.struct.image.GrayS32,boofcv.alg.InputSanityCheck,boofcv.alg.filter.convolve.normalized.ConvolveNormalizedNaive,boofcv.alg.filter.convolve.ConvolveImageNoBorder,boofcv.alg.filter.convolve.normalized.ConvolveNormalized_JustBorder)";
                $__params.add($param_Kernel1D_I32_1);
                $__params.add($param_GrayS32_2);
                $__params.add($param_GrayS32_3);
                $__params.add($param_InputSanityCheck_4);
                $__params.add($param_ConvolveNormalizedNaive_5);
                $__params.add($param_ConvolveImageNoBorder_6);
                $__params.add($param_ConvolveNormalized_JustBorder_7);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of vertical(Kernel1D_I32, GrayS16, GrayI16, InputSanityCheck, ConvolveNormalizedNaive, ConvolveImageNoBorder, ConvolveNormalized_JustBorder)
    public void vertical(boofcv.struct.convolve.Kernel1D_I32 $param_Kernel1D_I32_1, boofcv.struct.image.GrayS16 $param_GrayS16_2, boofcv.struct.image.GrayI16 $param_GrayI16_3, boofcv.alg.InputSanityCheck $param_InputSanityCheck_4, boofcv.alg.filter.convolve.normalized.ConvolveNormalizedNaive $param_ConvolveNormalizedNaive_5, boofcv.alg.filter.convolve.ConvolveImageNoBorder $param_ConvolveImageNoBorder_6, boofcv.alg.filter.convolve.normalized.ConvolveNormalized_JustBorder $param_ConvolveNormalized_JustBorder_7) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.vertical( $param_Kernel1D_I32_1,  $param_GrayS16_2,  $param_GrayI16_3,  $param_InputSanityCheck_4,  $param_ConvolveNormalizedNaive_5,  $param_ConvolveImageNoBorder_6,  $param_ConvolveNormalized_JustBorder_7);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.alg.filter.convolve.ConvolveNormalized.vertical(boofcv.struct.convolve.Kernel1D_I32,boofcv.struct.image.GrayS16,boofcv.struct.image.GrayI16,boofcv.alg.InputSanityCheck,boofcv.alg.filter.convolve.normalized.ConvolveNormalizedNaive,boofcv.alg.filter.convolve.ConvolveImageNoBorder,boofcv.alg.filter.convolve.normalized.ConvolveNormalized_JustBorder)";
                $__params.add($param_Kernel1D_I32_1);
                $__params.add($param_GrayS16_2);
                $__params.add($param_GrayI16_3);
                $__params.add($param_InputSanityCheck_4);
                $__params.add($param_ConvolveNormalizedNaive_5);
                $__params.add($param_ConvolveImageNoBorder_6);
                $__params.add($param_ConvolveNormalized_JustBorder_7);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of vertical(Kernel1D_F64, GrayF64, GrayF64, InputSanityCheck, ConvolveNormalizedNaive, ConvolveImageNoBorder, ConvolveNormalized_JustBorder)
    public void vertical(boofcv.struct.convolve.Kernel1D_F64 $param_Kernel1D_F64_1, boofcv.struct.image.GrayF64 $param_GrayF64_2, boofcv.struct.image.GrayF64 $param_GrayF64_3, boofcv.alg.InputSanityCheck $param_InputSanityCheck_4, boofcv.alg.filter.convolve.normalized.ConvolveNormalizedNaive $param_ConvolveNormalizedNaive_5, boofcv.alg.filter.convolve.ConvolveImageNoBorder $param_ConvolveImageNoBorder_6, boofcv.alg.filter.convolve.normalized.ConvolveNormalized_JustBorder $param_ConvolveNormalized_JustBorder_7) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.vertical( $param_Kernel1D_F64_1,  $param_GrayF64_2,  $param_GrayF64_3,  $param_InputSanityCheck_4,  $param_ConvolveNormalizedNaive_5,  $param_ConvolveImageNoBorder_6,  $param_ConvolveNormalized_JustBorder_7);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.alg.filter.convolve.ConvolveNormalized.vertical(boofcv.struct.convolve.Kernel1D_F64,boofcv.struct.image.GrayF64,boofcv.struct.image.GrayF64,boofcv.alg.InputSanityCheck,boofcv.alg.filter.convolve.normalized.ConvolveNormalizedNaive,boofcv.alg.filter.convolve.ConvolveImageNoBorder,boofcv.alg.filter.convolve.normalized.ConvolveNormalized_JustBorder)";
                $__params.add($param_Kernel1D_F64_1);
                $__params.add($param_GrayF64_2);
                $__params.add($param_GrayF64_3);
                $__params.add($param_InputSanityCheck_4);
                $__params.add($param_ConvolveNormalizedNaive_5);
                $__params.add($param_ConvolveImageNoBorder_6);
                $__params.add($param_ConvolveNormalized_JustBorder_7);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of vertical(Kernel1D_F32, GrayF32, GrayF32, InputSanityCheck, ConvolveNormalizedNaive, ConvolveImageNoBorder, ConvolveNormalized_JustBorder)
    public void vertical(boofcv.struct.convolve.Kernel1D_F32 $param_Kernel1D_F32_1, boofcv.struct.image.GrayF32 $param_GrayF32_2, boofcv.struct.image.GrayF32 $param_GrayF32_3, boofcv.alg.InputSanityCheck $param_InputSanityCheck_4, boofcv.alg.filter.convolve.normalized.ConvolveNormalizedNaive $param_ConvolveNormalizedNaive_5, boofcv.alg.filter.convolve.ConvolveImageNoBorder $param_ConvolveImageNoBorder_6, boofcv.alg.filter.convolve.normalized.ConvolveNormalized_JustBorder $param_ConvolveNormalized_JustBorder_7) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.vertical( $param_Kernel1D_F32_1,  $param_GrayF32_2,  $param_GrayF32_3,  $param_InputSanityCheck_4,  $param_ConvolveNormalizedNaive_5,  $param_ConvolveImageNoBorder_6,  $param_ConvolveNormalized_JustBorder_7);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.alg.filter.convolve.ConvolveNormalized.vertical(boofcv.struct.convolve.Kernel1D_F32,boofcv.struct.image.GrayF32,boofcv.struct.image.GrayF32,boofcv.alg.InputSanityCheck,boofcv.alg.filter.convolve.normalized.ConvolveNormalizedNaive,boofcv.alg.filter.convolve.ConvolveImageNoBorder,boofcv.alg.filter.convolve.normalized.ConvolveNormalized_JustBorder)";
                $__params.add($param_Kernel1D_F32_1);
                $__params.add($param_GrayF32_2);
                $__params.add($param_GrayF32_3);
                $__params.add($param_InputSanityCheck_4);
                $__params.add($param_ConvolveNormalizedNaive_5);
                $__params.add($param_ConvolveImageNoBorder_6);
                $__params.add($param_ConvolveNormalized_JustBorder_7);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of horizontal(Kernel1D_I32, GrayU8, GrayI8, InputSanityCheck, ConvolveNormalizedNaive, ConvolveImageNoBorder, ConvolveNormalized_JustBorder)
    public void horizontal(boofcv.struct.convolve.Kernel1D_I32 $param_Kernel1D_I32_1, boofcv.struct.image.GrayU8 $param_GrayU8_2, boofcv.struct.image.GrayI8 $param_GrayI8_3, boofcv.alg.InputSanityCheck $param_InputSanityCheck_4, boofcv.alg.filter.convolve.normalized.ConvolveNormalizedNaive $param_ConvolveNormalizedNaive_5, boofcv.alg.filter.convolve.ConvolveImageNoBorder $param_ConvolveImageNoBorder_6, boofcv.alg.filter.convolve.normalized.ConvolveNormalized_JustBorder $param_ConvolveNormalized_JustBorder_7) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.horizontal( $param_Kernel1D_I32_1,  $param_GrayU8_2,  $param_GrayI8_3,  $param_InputSanityCheck_4,  $param_ConvolveNormalizedNaive_5,  $param_ConvolveImageNoBorder_6,  $param_ConvolveNormalized_JustBorder_7);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.alg.filter.convolve.ConvolveNormalized.horizontal(boofcv.struct.convolve.Kernel1D_I32,boofcv.struct.image.GrayU8,boofcv.struct.image.GrayI8,boofcv.alg.InputSanityCheck,boofcv.alg.filter.convolve.normalized.ConvolveNormalizedNaive,boofcv.alg.filter.convolve.ConvolveImageNoBorder,boofcv.alg.filter.convolve.normalized.ConvolveNormalized_JustBorder)";
                $__params.add($param_Kernel1D_I32_1);
                $__params.add($param_GrayU8_2);
                $__params.add($param_GrayI8_3);
                $__params.add($param_InputSanityCheck_4);
                $__params.add($param_ConvolveNormalizedNaive_5);
                $__params.add($param_ConvolveImageNoBorder_6);
                $__params.add($param_ConvolveNormalized_JustBorder_7);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of horizontal(Kernel1D_I32, GrayS32, GrayS32, InputSanityCheck, ConvolveNormalizedNaive, ConvolveImageNoBorder, ConvolveNormalized_JustBorder)
    public void horizontal(boofcv.struct.convolve.Kernel1D_I32 $param_Kernel1D_I32_1, boofcv.struct.image.GrayS32 $param_GrayS32_2, boofcv.struct.image.GrayS32 $param_GrayS32_3, boofcv.alg.InputSanityCheck $param_InputSanityCheck_4, boofcv.alg.filter.convolve.normalized.ConvolveNormalizedNaive $param_ConvolveNormalizedNaive_5, boofcv.alg.filter.convolve.ConvolveImageNoBorder $param_ConvolveImageNoBorder_6, boofcv.alg.filter.convolve.normalized.ConvolveNormalized_JustBorder $param_ConvolveNormalized_JustBorder_7) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.horizontal( $param_Kernel1D_I32_1,  $param_GrayS32_2,  $param_GrayS32_3,  $param_InputSanityCheck_4,  $param_ConvolveNormalizedNaive_5,  $param_ConvolveImageNoBorder_6,  $param_ConvolveNormalized_JustBorder_7);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.alg.filter.convolve.ConvolveNormalized.horizontal(boofcv.struct.convolve.Kernel1D_I32,boofcv.struct.image.GrayS32,boofcv.struct.image.GrayS32,boofcv.alg.InputSanityCheck,boofcv.alg.filter.convolve.normalized.ConvolveNormalizedNaive,boofcv.alg.filter.convolve.ConvolveImageNoBorder,boofcv.alg.filter.convolve.normalized.ConvolveNormalized_JustBorder)";
                $__params.add($param_Kernel1D_I32_1);
                $__params.add($param_GrayS32_2);
                $__params.add($param_GrayS32_3);
                $__params.add($param_InputSanityCheck_4);
                $__params.add($param_ConvolveNormalizedNaive_5);
                $__params.add($param_ConvolveImageNoBorder_6);
                $__params.add($param_ConvolveNormalized_JustBorder_7);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of horizontal(Kernel1D_I32, GrayS16, GrayI16, InputSanityCheck, ConvolveNormalizedNaive, ConvolveImageNoBorder, ConvolveNormalized_JustBorder)
    public void horizontal(boofcv.struct.convolve.Kernel1D_I32 $param_Kernel1D_I32_1, boofcv.struct.image.GrayS16 $param_GrayS16_2, boofcv.struct.image.GrayI16 $param_GrayI16_3, boofcv.alg.InputSanityCheck $param_InputSanityCheck_4, boofcv.alg.filter.convolve.normalized.ConvolveNormalizedNaive $param_ConvolveNormalizedNaive_5, boofcv.alg.filter.convolve.ConvolveImageNoBorder $param_ConvolveImageNoBorder_6, boofcv.alg.filter.convolve.normalized.ConvolveNormalized_JustBorder $param_ConvolveNormalized_JustBorder_7) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.horizontal( $param_Kernel1D_I32_1,  $param_GrayS16_2,  $param_GrayI16_3,  $param_InputSanityCheck_4,  $param_ConvolveNormalizedNaive_5,  $param_ConvolveImageNoBorder_6,  $param_ConvolveNormalized_JustBorder_7);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.alg.filter.convolve.ConvolveNormalized.horizontal(boofcv.struct.convolve.Kernel1D_I32,boofcv.struct.image.GrayS16,boofcv.struct.image.GrayI16,boofcv.alg.InputSanityCheck,boofcv.alg.filter.convolve.normalized.ConvolveNormalizedNaive,boofcv.alg.filter.convolve.ConvolveImageNoBorder,boofcv.alg.filter.convolve.normalized.ConvolveNormalized_JustBorder)";
                $__params.add($param_Kernel1D_I32_1);
                $__params.add($param_GrayS16_2);
                $__params.add($param_GrayI16_3);
                $__params.add($param_InputSanityCheck_4);
                $__params.add($param_ConvolveNormalizedNaive_5);
                $__params.add($param_ConvolveImageNoBorder_6);
                $__params.add($param_ConvolveNormalized_JustBorder_7);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of horizontal(Kernel1D_F64, GrayF64, GrayF64, InputSanityCheck, ConvolveNormalizedNaive, ConvolveImageNoBorder, ConvolveNormalized_JustBorder)
    public void horizontal(boofcv.struct.convolve.Kernel1D_F64 $param_Kernel1D_F64_1, boofcv.struct.image.GrayF64 $param_GrayF64_2, boofcv.struct.image.GrayF64 $param_GrayF64_3, boofcv.alg.InputSanityCheck $param_InputSanityCheck_4, boofcv.alg.filter.convolve.normalized.ConvolveNormalizedNaive $param_ConvolveNormalizedNaive_5, boofcv.alg.filter.convolve.ConvolveImageNoBorder $param_ConvolveImageNoBorder_6, boofcv.alg.filter.convolve.normalized.ConvolveNormalized_JustBorder $param_ConvolveNormalized_JustBorder_7) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.horizontal( $param_Kernel1D_F64_1,  $param_GrayF64_2,  $param_GrayF64_3,  $param_InputSanityCheck_4,  $param_ConvolveNormalizedNaive_5,  $param_ConvolveImageNoBorder_6,  $param_ConvolveNormalized_JustBorder_7);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.alg.filter.convolve.ConvolveNormalized.horizontal(boofcv.struct.convolve.Kernel1D_F64,boofcv.struct.image.GrayF64,boofcv.struct.image.GrayF64,boofcv.alg.InputSanityCheck,boofcv.alg.filter.convolve.normalized.ConvolveNormalizedNaive,boofcv.alg.filter.convolve.ConvolveImageNoBorder,boofcv.alg.filter.convolve.normalized.ConvolveNormalized_JustBorder)";
                $__params.add($param_Kernel1D_F64_1);
                $__params.add($param_GrayF64_2);
                $__params.add($param_GrayF64_3);
                $__params.add($param_InputSanityCheck_4);
                $__params.add($param_ConvolveNormalizedNaive_5);
                $__params.add($param_ConvolveImageNoBorder_6);
                $__params.add($param_ConvolveNormalized_JustBorder_7);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of horizontal(Kernel1D_F32, GrayF32, GrayF32, InputSanityCheck, ConvolveNormalizedNaive, ConvolveImageNoBorder, ConvolveNormalized_JustBorder)
    public void horizontal(boofcv.struct.convolve.Kernel1D_F32 $param_Kernel1D_F32_1, boofcv.struct.image.GrayF32 $param_GrayF32_2, boofcv.struct.image.GrayF32 $param_GrayF32_3, boofcv.alg.InputSanityCheck $param_InputSanityCheck_4, boofcv.alg.filter.convolve.normalized.ConvolveNormalizedNaive $param_ConvolveNormalizedNaive_5, boofcv.alg.filter.convolve.ConvolveImageNoBorder $param_ConvolveImageNoBorder_6, boofcv.alg.filter.convolve.normalized.ConvolveNormalized_JustBorder $param_ConvolveNormalized_JustBorder_7) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.horizontal( $param_Kernel1D_F32_1,  $param_GrayF32_2,  $param_GrayF32_3,  $param_InputSanityCheck_4,  $param_ConvolveNormalizedNaive_5,  $param_ConvolveImageNoBorder_6,  $param_ConvolveNormalized_JustBorder_7);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.alg.filter.convolve.ConvolveNormalized.horizontal(boofcv.struct.convolve.Kernel1D_F32,boofcv.struct.image.GrayF32,boofcv.struct.image.GrayF32,boofcv.alg.InputSanityCheck,boofcv.alg.filter.convolve.normalized.ConvolveNormalizedNaive,boofcv.alg.filter.convolve.ConvolveImageNoBorder,boofcv.alg.filter.convolve.normalized.ConvolveNormalized_JustBorder)";
                $__params.add($param_Kernel1D_F32_1);
                $__params.add($param_GrayF32_2);
                $__params.add($param_GrayF32_3);
                $__params.add($param_InputSanityCheck_4);
                $__params.add($param_ConvolveNormalizedNaive_5);
                $__params.add($param_ConvolveImageNoBorder_6);
                $__params.add($param_ConvolveNormalized_JustBorder_7);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of convolve(Kernel2D_I32, GrayU8, GrayI8, InputSanityCheck, ConvolveNormalizedNaive, ConvolveImageNoBorder, ConvolveNormalized_JustBorder)
    public void convolve(boofcv.struct.convolve.Kernel2D_I32 $param_Kernel2D_I32_1, boofcv.struct.image.GrayU8 $param_GrayU8_2, boofcv.struct.image.GrayI8 $param_GrayI8_3, boofcv.alg.InputSanityCheck $param_InputSanityCheck_4, boofcv.alg.filter.convolve.normalized.ConvolveNormalizedNaive $param_ConvolveNormalizedNaive_5, boofcv.alg.filter.convolve.ConvolveImageNoBorder $param_ConvolveImageNoBorder_6, boofcv.alg.filter.convolve.normalized.ConvolveNormalized_JustBorder $param_ConvolveNormalized_JustBorder_7) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.convolve( $param_Kernel2D_I32_1,  $param_GrayU8_2,  $param_GrayI8_3,  $param_InputSanityCheck_4,  $param_ConvolveNormalizedNaive_5,  $param_ConvolveImageNoBorder_6,  $param_ConvolveNormalized_JustBorder_7);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.alg.filter.convolve.ConvolveNormalized.convolve(boofcv.struct.convolve.Kernel2D_I32,boofcv.struct.image.GrayU8,boofcv.struct.image.GrayI8,boofcv.alg.InputSanityCheck,boofcv.alg.filter.convolve.normalized.ConvolveNormalizedNaive,boofcv.alg.filter.convolve.ConvolveImageNoBorder,boofcv.alg.filter.convolve.normalized.ConvolveNormalized_JustBorder)";
                $__params.add($param_Kernel2D_I32_1);
                $__params.add($param_GrayU8_2);
                $__params.add($param_GrayI8_3);
                $__params.add($param_InputSanityCheck_4);
                $__params.add($param_ConvolveNormalizedNaive_5);
                $__params.add($param_ConvolveImageNoBorder_6);
                $__params.add($param_ConvolveNormalized_JustBorder_7);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of convolve(Kernel2D_I32, GrayS16, GrayI16, InputSanityCheck, ConvolveNormalizedNaive, ConvolveImageNoBorder, ConvolveNormalized_JustBorder)
    public void convolve(boofcv.struct.convolve.Kernel2D_I32 $param_Kernel2D_I32_1, boofcv.struct.image.GrayS16 $param_GrayS16_2, boofcv.struct.image.GrayI16 $param_GrayI16_3, boofcv.alg.InputSanityCheck $param_InputSanityCheck_4, boofcv.alg.filter.convolve.normalized.ConvolveNormalizedNaive $param_ConvolveNormalizedNaive_5, boofcv.alg.filter.convolve.ConvolveImageNoBorder $param_ConvolveImageNoBorder_6, boofcv.alg.filter.convolve.normalized.ConvolveNormalized_JustBorder $param_ConvolveNormalized_JustBorder_7) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.convolve( $param_Kernel2D_I32_1,  $param_GrayS16_2,  $param_GrayI16_3,  $param_InputSanityCheck_4,  $param_ConvolveNormalizedNaive_5,  $param_ConvolveImageNoBorder_6,  $param_ConvolveNormalized_JustBorder_7);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.alg.filter.convolve.ConvolveNormalized.convolve(boofcv.struct.convolve.Kernel2D_I32,boofcv.struct.image.GrayS16,boofcv.struct.image.GrayI16,boofcv.alg.InputSanityCheck,boofcv.alg.filter.convolve.normalized.ConvolveNormalizedNaive,boofcv.alg.filter.convolve.ConvolveImageNoBorder,boofcv.alg.filter.convolve.normalized.ConvolveNormalized_JustBorder)";
                $__params.add($param_Kernel2D_I32_1);
                $__params.add($param_GrayS16_2);
                $__params.add($param_GrayI16_3);
                $__params.add($param_InputSanityCheck_4);
                $__params.add($param_ConvolveNormalizedNaive_5);
                $__params.add($param_ConvolveImageNoBorder_6);
                $__params.add($param_ConvolveNormalized_JustBorder_7);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of convolve(Kernel2D_F64, GrayF64, GrayF64, InputSanityCheck, ConvolveNormalizedNaive, ConvolveImageNoBorder, ConvolveNormalized_JustBorder)
    public void convolve(boofcv.struct.convolve.Kernel2D_F64 $param_Kernel2D_F64_1, boofcv.struct.image.GrayF64 $param_GrayF64_2, boofcv.struct.image.GrayF64 $param_GrayF64_3, boofcv.alg.InputSanityCheck $param_InputSanityCheck_4, boofcv.alg.filter.convolve.normalized.ConvolveNormalizedNaive $param_ConvolveNormalizedNaive_5, boofcv.alg.filter.convolve.ConvolveImageNoBorder $param_ConvolveImageNoBorder_6, boofcv.alg.filter.convolve.normalized.ConvolveNormalized_JustBorder $param_ConvolveNormalized_JustBorder_7) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.convolve( $param_Kernel2D_F64_1,  $param_GrayF64_2,  $param_GrayF64_3,  $param_InputSanityCheck_4,  $param_ConvolveNormalizedNaive_5,  $param_ConvolveImageNoBorder_6,  $param_ConvolveNormalized_JustBorder_7);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.alg.filter.convolve.ConvolveNormalized.convolve(boofcv.struct.convolve.Kernel2D_F64,boofcv.struct.image.GrayF64,boofcv.struct.image.GrayF64,boofcv.alg.InputSanityCheck,boofcv.alg.filter.convolve.normalized.ConvolveNormalizedNaive,boofcv.alg.filter.convolve.ConvolveImageNoBorder,boofcv.alg.filter.convolve.normalized.ConvolveNormalized_JustBorder)";
                $__params.add($param_Kernel2D_F64_1);
                $__params.add($param_GrayF64_2);
                $__params.add($param_GrayF64_3);
                $__params.add($param_InputSanityCheck_4);
                $__params.add($param_ConvolveNormalizedNaive_5);
                $__params.add($param_ConvolveImageNoBorder_6);
                $__params.add($param_ConvolveNormalized_JustBorder_7);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of convolve(Kernel2D_F32, GrayF32, GrayF32, InputSanityCheck, ConvolveNormalizedNaive, ConvolveImageNoBorder, ConvolveNormalized_JustBorder)
    public void convolve(boofcv.struct.convolve.Kernel2D_F32 $param_Kernel2D_F32_1, boofcv.struct.image.GrayF32 $param_GrayF32_2, boofcv.struct.image.GrayF32 $param_GrayF32_3, boofcv.alg.InputSanityCheck $param_InputSanityCheck_4, boofcv.alg.filter.convolve.normalized.ConvolveNormalizedNaive $param_ConvolveNormalizedNaive_5, boofcv.alg.filter.convolve.ConvolveImageNoBorder $param_ConvolveImageNoBorder_6, boofcv.alg.filter.convolve.normalized.ConvolveNormalized_JustBorder $param_ConvolveNormalized_JustBorder_7) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.convolve( $param_Kernel2D_F32_1,  $param_GrayF32_2,  $param_GrayF32_3,  $param_InputSanityCheck_4,  $param_ConvolveNormalizedNaive_5,  $param_ConvolveImageNoBorder_6,  $param_ConvolveNormalized_JustBorder_7);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.alg.filter.convolve.ConvolveNormalized.convolve(boofcv.struct.convolve.Kernel2D_F32,boofcv.struct.image.GrayF32,boofcv.struct.image.GrayF32,boofcv.alg.InputSanityCheck,boofcv.alg.filter.convolve.normalized.ConvolveNormalizedNaive,boofcv.alg.filter.convolve.ConvolveImageNoBorder,boofcv.alg.filter.convolve.normalized.ConvolveNormalized_JustBorder)";
                $__params.add($param_Kernel2D_F32_1);
                $__params.add($param_GrayF32_2);
                $__params.add($param_GrayF32_3);
                $__params.add($param_InputSanityCheck_4);
                $__params.add($param_ConvolveNormalizedNaive_5);
                $__params.add($param_ConvolveImageNoBorder_6);
                $__params.add($param_ConvolveNormalized_JustBorder_7);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
