/*
 * Stub for class boofcv.factory.feature.associate.FactoryAssociation
 * Generated by Sapphire Compiler (sc).
 */
package boofcv.factory.feature.associate.stubs;


public final class FactoryAssociation_Stub extends boofcv.factory.feature.associate.FactoryAssociation implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public FactoryAssociation_Stub () {
        super();
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of scoreSad(Class)
    public boofcv.abst.feature.associate.ScoreAssociation scoreSad(java.lang.Class $param_Class_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.scoreSad( $param_Class_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public <D> boofcv.abst.feature.associate.ScoreAssociation<D> boofcv.factory.feature.associate.FactoryAssociation.scoreSad(java.lang.Class<D>)";
                $__params.add($param_Class_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((boofcv.abst.feature.associate.ScoreAssociation) $__result);
    }

    // Implementation of scoreNcc()
    public boofcv.abst.feature.associate.ScoreAssociation scoreNcc() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.scoreNcc();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public boofcv.abst.feature.associate.ScoreAssociation<boofcv.struct.feature.NccFeature> boofcv.factory.feature.associate.FactoryAssociation.scoreNcc()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((boofcv.abst.feature.associate.ScoreAssociation) $__result);
    }

    // Implementation of scoreHamming(Class)
    public boofcv.abst.feature.associate.ScoreAssociation scoreHamming(java.lang.Class $param_Class_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.scoreHamming( $param_Class_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public <D> boofcv.abst.feature.associate.ScoreAssociation<D> boofcv.factory.feature.associate.FactoryAssociation.scoreHamming(java.lang.Class<D>)";
                $__params.add($param_Class_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((boofcv.abst.feature.associate.ScoreAssociation) $__result);
    }

    // Implementation of scoreEuclidean(Class, boolean)
    public boofcv.abst.feature.associate.ScoreAssociation scoreEuclidean(java.lang.Class $param_Class_1, boolean $param_boolean_2) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.scoreEuclidean( $param_Class_1,  $param_boolean_2);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public <D> boofcv.abst.feature.associate.ScoreAssociation<D> boofcv.factory.feature.associate.FactoryAssociation.scoreEuclidean(java.lang.Class<D>,boolean)";
                $__params.add($param_Class_1);
                $__params.add($param_boolean_2);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((boofcv.abst.feature.associate.ScoreAssociation) $__result);
    }

    // Implementation of kdtree(int, int)
    public boofcv.abst.feature.associate.AssociateDescription kdtree(int $param_int_1, int $param_int_2) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.kdtree( $param_int_1,  $param_int_2);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public boofcv.abst.feature.associate.AssociateDescription<boofcv.struct.feature.TupleDesc_F64> boofcv.factory.feature.associate.FactoryAssociation.kdtree(int,int)";
                $__params.add($param_int_1);
                $__params.add($param_int_2);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((boofcv.abst.feature.associate.AssociateDescription) $__result);
    }

    // Implementation of kdRandomForest(int, int, int, int, long)
    public boofcv.abst.feature.associate.AssociateDescription kdRandomForest(int $param_int_1, int $param_int_2, int $param_int_3, int $param_int_4, long $param_long_5) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.kdRandomForest( $param_int_1,  $param_int_2,  $param_int_3,  $param_int_4,  $param_long_5);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public boofcv.abst.feature.associate.AssociateDescription<boofcv.struct.feature.TupleDesc_F64> boofcv.factory.feature.associate.FactoryAssociation.kdRandomForest(int,int,int,int,long)";
                $__params.add($param_int_1);
                $__params.add($param_int_2);
                $__params.add($param_int_3);
                $__params.add($param_int_4);
                $__params.add($param_long_5);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((boofcv.abst.feature.associate.AssociateDescription) $__result);
    }

    // Implementation of greedy(ScoreAssociation, double, boolean)
    public boofcv.abst.feature.associate.AssociateDescription greedy(boofcv.abst.feature.associate.ScoreAssociation $param_ScoreAssociation_1, double $param_double_2, boolean $param_boolean_3) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.greedy( $param_ScoreAssociation_1,  $param_double_2,  $param_boolean_3);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public <D> boofcv.abst.feature.associate.AssociateDescription<D> boofcv.factory.feature.associate.FactoryAssociation.greedy(boofcv.abst.feature.associate.ScoreAssociation<D>,double,boolean)";
                $__params.add($param_ScoreAssociation_1);
                $__params.add($param_double_2);
                $__params.add($param_boolean_3);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((boofcv.abst.feature.associate.AssociateDescription) $__result);
    }

    // Implementation of defaultScore(Class)
    public boofcv.abst.feature.associate.ScoreAssociation defaultScore(java.lang.Class $param_Class_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.defaultScore( $param_Class_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public <D> boofcv.abst.feature.associate.ScoreAssociation<D> boofcv.factory.feature.associate.FactoryAssociation.defaultScore(java.lang.Class<D>)";
                $__params.add($param_Class_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((boofcv.abst.feature.associate.ScoreAssociation) $__result);
    }
}
