/*
 * Stub for class boofcv.alg.distort.LensDistortionOps
 * Generated by Sapphire Compiler (sc).
 */
package boofcv.alg.distort.stubs;


public final class LensDistortionOps_Stub extends boofcv.alg.distort.LensDistortionOps implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public LensDistortionOps_Stub () {
        super();
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of transform_F64(AdjustmentType, CameraPinholeRadial, CameraPinholeRadial, boolean)
    public boofcv.struct.distort.Point2Transform2_F64 transform_F64(boofcv.alg.distort.AdjustmentType $param_AdjustmentType_1, boofcv.struct.calib.CameraPinholeRadial $param_CameraPinholeRadial_2, boofcv.struct.calib.CameraPinholeRadial $param_CameraPinholeRadial_3, boolean $param_boolean_4) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.transform_F64( $param_AdjustmentType_1,  $param_CameraPinholeRadial_2,  $param_CameraPinholeRadial_3,  $param_boolean_4);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public boofcv.struct.distort.Point2Transform2_F64 boofcv.alg.distort.LensDistortionOps.transform_F64(boofcv.alg.distort.AdjustmentType,boofcv.struct.calib.CameraPinholeRadial,boofcv.struct.calib.CameraPinholeRadial,boolean)";
                $__params.add($param_AdjustmentType_1);
                $__params.add($param_CameraPinholeRadial_2);
                $__params.add($param_CameraPinholeRadial_3);
                $__params.add($param_boolean_4);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((boofcv.struct.distort.Point2Transform2_F64) $__result);
    }

    // Implementation of transform_F32(AdjustmentType, CameraPinholeRadial, CameraPinholeRadial, boolean)
    public boofcv.struct.distort.Point2Transform2_F32 transform_F32(boofcv.alg.distort.AdjustmentType $param_AdjustmentType_1, boofcv.struct.calib.CameraPinholeRadial $param_CameraPinholeRadial_2, boofcv.struct.calib.CameraPinholeRadial $param_CameraPinholeRadial_3, boolean $param_boolean_4) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.transform_F32( $param_AdjustmentType_1,  $param_CameraPinholeRadial_2,  $param_CameraPinholeRadial_3,  $param_boolean_4);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public boofcv.struct.distort.Point2Transform2_F32 boofcv.alg.distort.LensDistortionOps.transform_F32(boofcv.alg.distort.AdjustmentType,boofcv.struct.calib.CameraPinholeRadial,boofcv.struct.calib.CameraPinholeRadial,boolean)";
                $__params.add($param_AdjustmentType_1);
                $__params.add($param_CameraPinholeRadial_2);
                $__params.add($param_CameraPinholeRadial_3);
                $__params.add($param_boolean_4);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((boofcv.struct.distort.Point2Transform2_F32) $__result);
    }

    // Implementation of transformPoint(CameraPinholeRadial)
    public boofcv.alg.distort.LensDistortionNarrowFOV transformPoint(boofcv.struct.calib.CameraPinholeRadial $param_CameraPinholeRadial_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.transformPoint( $param_CameraPinholeRadial_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public boofcv.alg.distort.LensDistortionNarrowFOV boofcv.alg.distort.LensDistortionOps.transformPoint(boofcv.struct.calib.CameraPinholeRadial)";
                $__params.add($param_CameraPinholeRadial_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((boofcv.alg.distort.LensDistortionNarrowFOV) $__result);
    }

    // Implementation of roundInside(RectangleLength2D_F64)
    public void roundInside(georegression.struct.shapes.RectangleLength2D_F64 $param_RectangleLength2D_F64_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.roundInside( $param_RectangleLength2D_F64_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.alg.distort.LensDistortionOps.roundInside(georegression.struct.shapes.RectangleLength2D_F64)";
                $__params.add($param_RectangleLength2D_F64_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of roundInside(RectangleLength2D_F32)
    public void roundInside(georegression.struct.shapes.RectangleLength2D_F32 $param_RectangleLength2D_F32_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.roundInside( $param_RectangleLength2D_F32_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.alg.distort.LensDistortionOps.roundInside(georegression.struct.shapes.RectangleLength2D_F32)";
                $__params.add($param_RectangleLength2D_F32_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of imageRemoveDistortion(AdjustmentType, BorderType, CameraPinholeRadial, CameraPinholeRadial, ImageType, FactoryImageBorder, FactoryInterpolation, FactoryDistort)
    public boofcv.alg.distort.ImageDistort imageRemoveDistortion(boofcv.alg.distort.AdjustmentType $param_AdjustmentType_1, boofcv.core.image.border.BorderType $param_BorderType_2, boofcv.struct.calib.CameraPinholeRadial $param_CameraPinholeRadial_3, boofcv.struct.calib.CameraPinholeRadial $param_CameraPinholeRadial_4, boofcv.struct.image.ImageType $param_ImageType_5, boofcv.core.image.border.FactoryImageBorder $param_FactoryImageBorder_6, boofcv.factory.interpolate.FactoryInterpolation $param_FactoryInterpolation_7, boofcv.factory.distort.FactoryDistort $param_FactoryDistort_8) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.imageRemoveDistortion( $param_AdjustmentType_1,  $param_BorderType_2,  $param_CameraPinholeRadial_3,  $param_CameraPinholeRadial_4,  $param_ImageType_5,  $param_FactoryImageBorder_6,  $param_FactoryInterpolation_7,  $param_FactoryDistort_8);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public <T> boofcv.alg.distort.ImageDistort<T, T> boofcv.alg.distort.LensDistortionOps.imageRemoveDistortion(boofcv.alg.distort.AdjustmentType,boofcv.core.image.border.BorderType,boofcv.struct.calib.CameraPinholeRadial,boofcv.struct.calib.CameraPinholeRadial,boofcv.struct.image.ImageType<T>,boofcv.core.image.border.FactoryImageBorder,boofcv.factory.interpolate.FactoryInterpolation,boofcv.factory.distort.FactoryDistort)";
                $__params.add($param_AdjustmentType_1);
                $__params.add($param_BorderType_2);
                $__params.add($param_CameraPinholeRadial_3);
                $__params.add($param_CameraPinholeRadial_4);
                $__params.add($param_ImageType_5);
                $__params.add($param_FactoryImageBorder_6);
                $__params.add($param_FactoryInterpolation_7);
                $__params.add($param_FactoryDistort_8);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((boofcv.alg.distort.ImageDistort) $__result);
    }

    // Implementation of boundBoxInside(int, int, PixelTransform2_F64)
    public georegression.struct.shapes.RectangleLength2D_F64 boundBoxInside(int $param_int_1, int $param_int_2, boofcv.struct.distort.PixelTransform2_F64 $param_PixelTransform2_F64_3) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.boundBoxInside( $param_int_1,  $param_int_2,  $param_PixelTransform2_F64_3);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public georegression.struct.shapes.RectangleLength2D_F64 boofcv.alg.distort.LensDistortionOps.boundBoxInside(int,int,boofcv.struct.distort.PixelTransform2_F64)";
                $__params.add($param_int_1);
                $__params.add($param_int_2);
                $__params.add($param_PixelTransform2_F64_3);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((georegression.struct.shapes.RectangleLength2D_F64) $__result);
    }

    // Implementation of boundBoxInside(int, int, PixelTransform2_F32)
    public georegression.struct.shapes.RectangleLength2D_F32 boundBoxInside(int $param_int_1, int $param_int_2, boofcv.struct.distort.PixelTransform2_F32 $param_PixelTransform2_F32_3) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.boundBoxInside( $param_int_1,  $param_int_2,  $param_PixelTransform2_F32_3);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public georegression.struct.shapes.RectangleLength2D_F32 boofcv.alg.distort.LensDistortionOps.boundBoxInside(int,int,boofcv.struct.distort.PixelTransform2_F32)";
                $__params.add($param_int_1);
                $__params.add($param_int_2);
                $__params.add($param_PixelTransform2_F32_3);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((georegression.struct.shapes.RectangleLength2D_F32) $__result);
    }
}
