/*
 * Stub for class boofcv.alg.filter.blur.impl.ImplMedianSortEdgeNaive
 * Generated by Sapphire Compiler (sc).
 */
package boofcv.alg.filter.blur.impl.stubs;


public final class ImplMedianSortEdgeNaive_Stub extends boofcv.alg.filter.blur.impl.ImplMedianSortEdgeNaive implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public ImplMedianSortEdgeNaive_Stub () {
        super();
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of process(GrayI, GrayI, int, int[])
    public void process(boofcv.struct.image.GrayI $param_GrayI_1, boofcv.struct.image.GrayI $param_GrayI_2, int $param_int_3, int[] $param_arrayOf_int_4) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.process( $param_GrayI_1,  $param_GrayI_2,  $param_int_3,  $param_arrayOf_int_4);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.alg.filter.blur.impl.ImplMedianSortEdgeNaive.process(boofcv.struct.image.GrayI,boofcv.struct.image.GrayI,int,int[])";
                $__params.add($param_GrayI_1);
                $__params.add($param_GrayI_2);
                $__params.add($param_int_3);
                $__params.add($param_arrayOf_int_4);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of process(GrayF32, GrayF32, int, float[])
    public void process(boofcv.struct.image.GrayF32 $param_GrayF32_1, boofcv.struct.image.GrayF32 $param_GrayF32_2, int $param_int_3, float[] $param_arrayOf_float_4) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.process( $param_GrayF32_1,  $param_GrayF32_2,  $param_int_3,  $param_arrayOf_float_4);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.alg.filter.blur.impl.ImplMedianSortEdgeNaive.process(boofcv.struct.image.GrayF32,boofcv.struct.image.GrayF32,int,float[])";
                $__params.add($param_GrayF32_1);
                $__params.add($param_GrayF32_2);
                $__params.add($param_int_3);
                $__params.add($param_arrayOf_float_4);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
