/*
 * Stub for class boofcv.alg.filter.blur.impl.ImplMedianHistogramInner
 * Generated by Sapphire Compiler (sc).
 */
package boofcv.alg.filter.blur.impl.stubs;


public final class ImplMedianHistogramInner_Stub extends boofcv.alg.filter.blur.impl.ImplMedianHistogramInner implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public ImplMedianHistogramInner_Stub () {
        super();
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of process(GrayU8, GrayU8, int, int[], int[])
    public void process(boofcv.struct.image.GrayU8 $param_GrayU8_1, boofcv.struct.image.GrayU8 $param_GrayU8_2, int $param_int_3, int[] $param_arrayOf_int_4, int[] $param_arrayOf_int_5) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.process( $param_GrayU8_1,  $param_GrayU8_2,  $param_int_3,  $param_arrayOf_int_4,  $param_arrayOf_int_5);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void boofcv.alg.filter.blur.impl.ImplMedianHistogramInner.process(boofcv.struct.image.GrayU8,boofcv.struct.image.GrayU8,int,int[],int[])";
                $__params.add($param_GrayU8_1);
                $__params.add($param_GrayU8_2);
                $__params.add($param_int_3);
                $__params.add($param_arrayOf_int_4);
                $__params.add($param_arrayOf_int_5);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
