/*
 * Stub for class boofcv.factory.transform.wavelet.GFactoryWavelet
 * Generated by Sapphire Compiler (sc).
 */
package boofcv.factory.transform.wavelet.stubs;


public final class GFactoryWavelet_Stub extends boofcv.factory.transform.wavelet.GFactoryWavelet implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public GFactoryWavelet_Stub () {
        super();
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of haar(Class)
    public boofcv.struct.wavelet.WaveletDescription haar(java.lang.Class $param_Class_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.haar( $param_Class_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public <C,T> boofcv.struct.wavelet.WaveletDescription<C> boofcv.factory.transform.wavelet.GFactoryWavelet.haar(java.lang.Class<T>)";
                $__params.add($param_Class_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((boofcv.struct.wavelet.WaveletDescription) $__result);
    }

    // Implementation of daubJ(Class, int)
    public boofcv.struct.wavelet.WaveletDescription daubJ(java.lang.Class $param_Class_1, int $param_int_2) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.daubJ( $param_Class_1,  $param_int_2);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public <C,T> boofcv.struct.wavelet.WaveletDescription<C> boofcv.factory.transform.wavelet.GFactoryWavelet.daubJ(java.lang.Class<T>,int)";
                $__params.add($param_Class_1);
                $__params.add($param_int_2);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((boofcv.struct.wavelet.WaveletDescription) $__result);
    }

    // Implementation of coiflet(Class, int)
    public boofcv.struct.wavelet.WaveletDescription coiflet(java.lang.Class $param_Class_1, int $param_int_2) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.coiflet( $param_Class_1,  $param_int_2);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public <C,T> boofcv.struct.wavelet.WaveletDescription<C> boofcv.factory.transform.wavelet.GFactoryWavelet.coiflet(java.lang.Class<T>,int)";
                $__params.add($param_Class_1);
                $__params.add($param_int_2);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((boofcv.struct.wavelet.WaveletDescription) $__result);
    }

    // Implementation of biorthogoal(Class, int, BorderType, UtilWavelet)
    public boofcv.struct.wavelet.WaveletDescription biorthogoal(java.lang.Class $param_Class_1, int $param_int_2, boofcv.core.image.border.BorderType $param_BorderType_3, boofcv.alg.transform.wavelet.UtilWavelet $param_UtilWavelet_4) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.biorthogoal( $param_Class_1,  $param_int_2,  $param_BorderType_3,  $param_UtilWavelet_4);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public <C,T> boofcv.struct.wavelet.WaveletDescription<C> boofcv.factory.transform.wavelet.GFactoryWavelet.biorthogoal(java.lang.Class<T>,int,boofcv.core.image.border.BorderType,boofcv.alg.transform.wavelet.UtilWavelet)";
                $__params.add($param_Class_1);
                $__params.add($param_int_2);
                $__params.add($param_BorderType_3);
                $__params.add($param_UtilWavelet_4);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((boofcv.struct.wavelet.WaveletDescription) $__result);
    }
}
